apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: catalog-service
build:
  local:
  artifacts:
    - image: catalog-service
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - GOOGLE_RUNTIME_VERSION=17
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/service.yml
